[workspace]
resolver = "2"

members = [
    "wie",
    "wie_cli",
    "wie_backend",
    "wie_base",
    "wie_core_arm",
    "wie_vendor_ktf",
    "wie_wipi_c",
    "wie_wipi_java",
]

[workspace.dependencies]
anyhow = { version = "^1.0", default-features = false }
async-trait = { version = "^0.1", default-features = false }
bitflags = { version = "^2.3", default-features = false }
bytemuck = { version = "^1.13", default-features = false, features = ["derive"] }
tracing = { version = "^0.1", default-features = false, features = ["attributes"] }
