[workspace]
resolver = "2"

members = [
    "crates/wie",
    "crates/wie_backend",
    "crates/wie_base",
    "crates/wie_core_arm",
    "crates/wie_vendor_ktf",
    "crates/wie_wipi_c",
    "crates/wie_wipi_java",
    "frontend/cli",
]

[workspace.dependencies]
anyhow = { version = "^1.0", default-features = false }
async-trait = { version = "^0.1", default-features = false }
bitflags = { version = "^2.3", default-features = false }
bytemuck = { version = "^1.13", default-features = false, features = ["derive"] }
tracing = { version = "^0.1", default-features = false, features = ["attributes"] }
