[package]
name = "wie_ktf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

async-recursion = { version = "^1.0" }

jvm = { git = "https://github.com/dlunch/RustJava.git" }
java_runtime = { git = "https://github.com/dlunch/RustJava.git" }
java_runtime_base = { git = "https://github.com/dlunch/RustJava.git" }

wie_backend = { path = "../wie_backend" }
wie_base = { path = "../wie_base" }
wie_core_arm = { path = "../wie_core_arm" }
wie_impl_wipi_c = { path = "../wie_impl_wipi_c" }
wie_impl_java = { path = "../wie_impl_java" }

[dev-dependencies]
futures-test = { version = "^0.3" }
