[package]
name = "wie"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }

zip = { version = "^0.6" }

wie_backend = { path = "../wie_backend" }
wie_vendor_ktf = { path = "../wie_vendor_ktf" }
