[package]
name = "wie_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "^1.0", features = ["backtrace"] }
clap = { version = "^4.4", features = ["derive"] }
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }

wie = { path = "../wie" }
wie_vendor_ktf = { path = "../wie_vendor_ktf" }
