[package]
name = "wie_backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

encoding_rs = { version = "^0.8" }
image = { version = "^0.24", features = ["bmp", "png"], default-features = false }
num-traits = { version = "^0.2" }
piet = { version = "^0.6" }
piet-common = { version = "^0.6" }
rodio = { version = "^0.17", default-features = false }
zip = { version = "^0.6", features = ["deflate"], default-features = false }

smaf = { git = "https://github.com/dlunch/smaf.git" }
smaf_player = { git = "https://github.com/dlunch/smaf.git" }

wie_base = { path = "../wie_base" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
directories = { version = "^5.0" }
