[package]
name = "wie_backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }


image = { version = "^0.24" }
softbuffer = { version = "^0.3" }
winit = { version = "0.28.0", features = ["wayland"] }
zip = { version = "^0.6", default-features = false }

wie_base = { path = "../wie_base" }
