[package]
name = "wie_backend"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

encoding_rs = { version = "^0.8" }
image = { version = "^0.24" }
num-traits = { version = "^0.2" }
piet = { version = "^0.6" }
piet-common = { version = "^0.6" }
zip = { version = "^0.6", features = ["deflate"], default-features = false }

wie_base = { path = "../wie_base" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
time = { version = "^0.3", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
time = { version = "^0.3" }
directories = { version = "^5.0" }
