[package]
name = "wie_skt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

wie_backend = { path = "../wie_backend" }
wie_base = { path = "../wie_base" }
wie_core_jvm = { path = "../wie_core_jvm" }
wie_impl_wipi_c = { path = "../wie_impl_wipi_c" }
wie_impl_java = { path = "../wie_impl_java" }

jvm = { git = "https://github.com/dlunch/jvm.git" }
