[package]
name = "wie_backend"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
softbuffer = { version = "^0.3" }
winit = { version = "0.28.0", features = ["wayland"] }

wie_base = { path = "../wie_base" }