[package]
name = "wie_core_arm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

armv4t_emu = { version = "^0.1" }
unicorn-engine = { version = "^2.0" }
capstone = { version = "^0.11" }

wie_backend = { path = "../wie_backend" }
wie_base = { path = "../wie_base" }
