[package]
name = "wie_common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }
