[package]
name = "wie_base"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
bytemuck = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
