[package]
name = "wie_wipi_c"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytemuck = { workspace = true }
tracing = { workspace = true }

wie_common = { path = "../wie_common" }
wie_backend = { path = "../wie_backend" }

[dev-dependencies]
futures-test = { version = "^0.3" }
